apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s # By default, scrape targets every 15 seconds.

      # Attach these labels to any time series or alerts when communicating with
      # external systems (federation, remote storage, Alertmanager).
      external_labels:
        monitor: 'kubeflow-monitor'

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: 'prometheus'

        # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 5s

        static_configs:
          - targets: ['localhost:9090']

      # Monitoring ml-pipeline (aka Kubeflow Pipelines API server)
      - job_name: 'ml-pipeline'
        scrape_interval: 15s
        static_configs:
          - targets: ['ml-pipeline.kubeflow:8888']
      
      # Monitoring katib-controller
      - job_name: 'katib-controller'
        scrape_interval: 15s
        scheme: http
        static_configs:
          - targets: ['katib-controller.kubeflow:8080']

      # Monitoring katib-controller
      - job_name: 'kfserving-controller-manager-metrics-service'
        scrape_interval: 15s
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets: ['kfserving-controller-manager-metrics-service.kubeflow:8443']

      # Monitoring TF and around
      - job_name: 'learning-engines'
        scrape_interval: 15s
        static_configs:
          - targets: ['pytorch-operator.kubeflow:8443', 'tf-job-operator.kubeflow:8443']
      
      # Monitoring TF and around
      - job_name: 'learning-engines-https'
        scrape_interval: 15s
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets: ['tensorboard-controller-controller-manager-metrics-service.kubeflow:8443']

      # Monitoring pods
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

kind: ConfigMap
metadata:
  name: prometheus-configmap