apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow-monitoring
namePrefix: kubeflow-
resources:
- namespace.yaml
- configmap.yaml
- sa.yaml
- role.yaml
- rolebinding.yaml
- service.yaml
- deployment.yaml
images:
  - name: prom/prometheus
#    newName: docker.dyn.ntnxdpro.com/prom/prometheus
    newTag: latest
